# Generated by Django 3.2.20 on 2024-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20240428_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
